[package]
name = "typewriter"
version = "0.1.0"
description = "Turn your keyboard into a typewriter"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rdev = "0.5.3"
rodio = { version = "0.17.1", default-features = false, features = [
  "symphonia-mp3",
] }
rust-embed = "8.0.0"
thiserror = "1.0.48"
tokio = { version = "1.32.0", features = ["full"] }
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.17", features = ["env-filter"] }
clap = { version = "4.4.4", features = ["derive", "env", "wrap_help", "cargo"] }

[dev-dependencies]
pretty_assertions = "1.4.0"
