[package]
name = "typewriter"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rdev = "0.5.3"
rodio = { version = "0.17.1", default-features = false, features = [
  "symphonia-mp3",
] }
tokio = { version = "1.32.0", features = ["full"] }
