[[sound_preset]]
name = "default"
key_config = [
  { event = "key_press", keys = "Return", files = [
    { path = "ding.mp3", volume = 1.0 },
  ] },
  { event = "key_press", keys = ".*", files = [
    { path = "keydown.mp3", volume = 1.0 },
  ] },
  { event = "key_release", keys = ".*", files = [
    { path = "keyup.mp3", volume = 1.0 },
  ] },
]
disabled_keys = []

[[sound_preset]]
name = "basic"
key_config = [
  { event = "key_press", keys = "Return", files = [
    { path = "newline.mp3" },
  ] },
  { event = "key_press", keys = ".*", files = [
    { path = "keystroke.mp3" },
  ] },
]
disabled_keys = ["UpArrow", "DownArrow", "LeftArrow", "RightArrow", "Backspace"]

# It dings, and it dongs. Nuff' said.
# With this rather more calming experience maybe you will think twice
# before typing down passive aggressive emails.
[[sound_preset]]
name = "musicbox"
key_config = [
  { event = "key_press", keys = ".*", files = [
    { path = "mbox1.mp3" },
    { path = "mbox2.mp3" },
    { path = "mbox3.mp3" },
    { path = "mbox4.mp3" },
    { path = "mbox5.mp3" },
    { path = "mbox6.mp3" },
    { path = "mbox7.mp3" },
    { path = "mbox8.mp3" },
  ], strategy = "random" },
]
disabled_keys = []

[[sound_preset]]
name = "ducktilo"
key_config = [
  { event = "key_press", keys = ".*", files = [
    { path = "quack.mp3", volume = 5.0 },
  ] },
]
disabled_keys = []
